tasks:
  HelloWorld:
    # task name
    name: "Hello World"

    # string for scheduling in crontab-like syntax (see https://crontab.guru).
    schedule: "* * * * *" # minute, hour, day, month, day_of_week

    # scenario type
    scenario: "hello_world"

    # transport type
    notifier: "stdout"

# database settings section (optional)
database:
  # hostname or IP address of a MongoDB instance to connect to
  # see <https://api.mongodb.com/python/current/api/pymongo/mongo_client.html>
  host: "mongodb"

  # port of a MongoDB instance
  port: 27017

  # name of the database
  name: "manager"

# proxy for performing tasks
# tor proxy config
proxy:
  # protocol of proxy
  protocol: "socks5"

  # host of proxy
  host: "localhost"

  # port of proxy
  port: 9050

  # username: "u53r14"

  # password: "p455w0rd88"